### ISSUE TITLE
Correct UML Notation

### ISSUE THREAD

**Issue by loibnerg** [ossdcfos/easyuml#6]
Is there a way to change the representation of the Diagrams to the UML Standard Notation?

E.g. for Attributes:

Currently it is formated like this: "- String name"
According to UML it should look like this: "- name:String"

Is there a way to have the class diagrams displayed in UML notation?

Kind regards,
Gernot Loibner
Teacher at HTBLA Kaindorf an der Sulm

**Comment by PaquitoLagra** [comment]
Couldn't this be made a preference that we can set to suit our environment?

**Comment by PaquitoLagra** [comment]
Students are taught one thing in class, then when they go to do their assignments the tool has it differently.
This can lead to confusion & wasted time, both for the tutor & the student.
